### ISSUE TITLE
Add base structure and functionality

### ISSUE THREAD

**Issue by Sebastianjohansson123** [Sebastianjohansson123/Bumpy---The-game#1]
Add base structure and functionality to the game, including: 
Backgroundimage 
Platforms
Bumpy

**Comment by Sebastianjohansson123** [comment]
En branch bara för oss! Va kul vi ska ha!! :D

**Comment by nathaliegustafsson** [comment]
Woho!!

**Comment by Emil-Helge** [comment]
Jag har gjort en pull från main så att typescript filerna som vi satt med idag också befinner sig i den här branchen :)
